config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'about'   => 'pages#about'
  get 'contact' => 'pages#contact'

  get 'signup' => 'users#new'
  resources :users # adds restful routes

  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/search.rb
class Search < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :job_title, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :searches, dependent: :destroy

  # Virtual attribute
  attr_accessor :remember_token

  #before_save { email.downcase! }

  # Force email addresses to be lowercase
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  # Save a securely hashed password_digest attribute to the db
  # Two virtual attributes (password and password_confirmation) + presence validations
  # Auth method build in
  has_secure_password

  # http://www.zorched.net/2009/05/08/password-strength-validation-with-regular-expressions/
  # Zero-width positive lookahead assertions
  # @todo Need test for this
  VALID_PASSWORD_REGEX = /(?=.*[a-z])(?=.*[\d])(?=.*[\W])(?=.*[A-Z])/

  # Virtual Model Attributes from has_secure_password
  validates :password, presence: true, length: { minimum: 8 }, format: { with: VALID_PASSWORD_REGEX }, allow_blank: true

  # Return the hash digest of the given string
  # Necessary to hash passwords outside the has_secure_password
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Return a random token for remember digest (cookies)
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    # set the class variable to be a new token (22 character string)
    self.remember_token = User.new_token

    # Update the remember digest db column with a hashed version of the token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forget a user cookie
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Include the session helper in the application wide scope
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      # Log the user in with the sessionHelper
      log_in user

      # Remember me
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)

      redirect_back_or user
    else
      # Flash.now is a special variant to be used with render
      # Flash can be reused on redirect
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  def destroy
    # only log out if already logged in
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # Call the logged_in_user method before the update and edit action only
  before_action :logged_in_user, only: [:edit, :update]

  # Check for the correct user on the edit and update actions
  before_action :correct_user, only: [:edit, :update]

  def show
    # Find user by route id
    @user = User.find(params[:id])
  end

  def new
    # A user object for the form
    @user = User.new
  end

  def create
    # Pass in the strong parameters
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "Welcome to CityFit"
      redirect_to @user
    else
      render 'new'
    end
  end

  # @user defined in correct_user filter
  def edit
  end

  # @user defined in correct_user filter
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

    private

      # Strong Parameters
      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
      end

      # Confirms a logged-in user.
      def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to login_url
        end
      end

      # Confirms the correct user.
      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_url) unless current_user?(@user)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(active_title = '')
    base_title = "CityFit: Solving couples two body problem"
    if active_title.empty?
      # return the base title essentially
      base_title
    else
      # return the concatentation
      "#{active_title} | #{base_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Log the user in
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    # Call user method
    user.remember

    # Set cookie
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Return true if the given user is the current user
  def current_user?(user)
    user == current_user
  end

  # FInd user by id unless current user already set
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise
  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Log out
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<%= link_to 'Contact', contact_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Brand", root_path, class: 'navbar-brand' %>
    </div>


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', about_path %></li>

        <% if logged_in? %>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Searches", "#" %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", logout_path, { method: 'delete' } %>
            </ul>
          </li>

        <% else %>
          <li><%= link_to 'Login', login_path %>
          <li><%= link_to 'Sign Up', signup_path %></li>
        <% end %>



      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'layouts/header' %>

    <div class="container">

      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>

      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_error.html.erb
<!-- Change @user to be dynamic variable -->
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>

  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>

            <%= render 'shared/error' %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.submit "Create an account", class: 'btn btn-success' %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "User Show") %>
<h1>Profile</h1>
<%= @user.name %>, <%= @user.email %>